name: Generate Proto Buffers

on:
  push:
    branches: [main]
    paths:
      - '**/*.proto'

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Install protoc
        uses: arduino/setup-protoc@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install protoc plugins
        run: |
          go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
          go install github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-grpc-gateway@latest

      - name: Generate code
        run: make gen-proto

      - name: Commit generated code
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'chore: auto-generate protobuf Go code'
          file_pattern: '*.pb.go *_grpc.pb.go *.pb.gw.go'
